language: java

env:
  global:
    - CC_TEST_REPORTER_ID=ac8d62ca68293f4f48785a06e5f6ff4fb73aa9e04a9c3cee0595f0a7af011e57

jdk:
  - openjdk8

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
