version: "3"
services:
  semillero-db:
    image: mariadb:10.3
    volumes:
      - semillero-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TERM=xterm
    ports:
      - "3307:3306"
volumes:
  - semillero_semillero-mariadb:
      external: true  
